# Generated by Django 6.0.3 on 2026-03-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ws_number', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('looked_by', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=500)),
                ('date_received', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='work_station',
        ),
    ]
